apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
      - name: resume-app
        image: nikhilck/resume-app-nginx:3.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  selector:
    app: resume-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure 
spec:
  tls:
  - hosts:
    - nikhilchavan.info
    secretName: nikhilchavan-info-tls 
  rules:
  - host: nikhilchavan.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resume-service
            port:
              number: 80
---
