apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
      - name: resume-app
        image: nikhil398/resume-app:6.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: default
spec:
  selector:
    app: resume-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nikhilchavan-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"  # Correct for Traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - nikhilchavan.info
      secretName: nikhilchavan-tls  # Matches the TLS Secret name
  rules:
    - host: nikhilchavan.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-service
                port:
                  number: 80
---
